# Generated by Django 5.0.3 on 2024-05-10 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmes', '0002_alter_listafilmes_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('Id_sessao', models.AutoField(primary_key=True, serialize=False)),
                ('data_sessao', models.DateField(verbose_name='Data da Sessão')),
                ('horario_sessao', models.TimeField(verbose_name='Horário da Sessão')),
                ('dub_leg', models.CharField(choices=[('L', 'Legendado'), ('D', 'Dublado')], max_length=1)),
                ('modo_2d_3d', models.CharField(choices=[('2', '2D'), ('3', '3D')], max_length=1)),
                ('assentos', models.CharField(default='eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', max_length=128)),
                ('Id_filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.listafilmes')),
            ],
        ),
    ]
