# Generated by Django 5.0.3 on 2024-05-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_sessoes_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessoes',
            options={'ordering': ['-Id_filme']},
        ),
    ]
