# Generated by Django 5.0.3 on 2024-06-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_sessoes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_preco',
            fields=[
                ('id_produto', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
            ],
        ),
    ]
