# Generated by Django 5.0.3 on 2024-03-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
